# Serving
baseurl: "" # does not include hostname

# Outputting
permalink:     /:year/:month/:day/:title/

title:        aeb.sr
tagline:      'Code. Pixels. Words.'
description:  'Opinionated dapper developer, promoting diversity in tech.'

sass:
  style: :compressed
