title:        aeb.sr
tagline:      'Code. Pixels. Words.'
description:  'Opinionated dapper developer, promoting diversity in tech.'
# Omit trailing slashes from your site url
url:          http://aeb.sr
author:
  name:       'Antoine Butler'
  bio:        'A designer, developer and musician working for <a href="http://hzdg.com">HZ</a>. His opinions are his own, and often offend. <a href="mailto:antoinebsr@gmail.com?subject=Hi">Say Hi.</a>'
  email:      'antoinebsr@gmail.com'
permalink:    pretty
pygments:     true
markdown:     redcarpet
paginate:     99

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

links:
  - title: About
    url: /about
  - title: Twitter
    url: http://twitter.com/aebsr
    external: true
  - title: Github
    url: http://github.com/aebsr
    external: true
  - title: LinkedIn
    url: http://www.linkedin.com/in/aebsr
    external: true
