# Serving
baseurl: "" # does not include hostname

# Outputting
permalink:     /notebook/:year/:month/:day/:title/

title:        'aeb.sr a.k.a Antoine Butler Sr'
tagline:      'Code. Pixels. Words.'
description:  'Purveyor of quirky verbosity, parables and dope rhymes. Maker. Rider. Gambler. Shooter. UI Engineer.'

sass:
  style: :compressed

include: [.htaccess]
